TYPO3:
  # TYPO3CR:
  #   contentDimensions:
  #     'language':
  #       label: 'Sprache'
  #       icon: 'icon-language'
  #       # The default dimension that is applied when creating nodes without specifying a dimension
  #       default: 'en'
  #       # The default preset to use if no URI segment was given when resolving languages in the router
  #       defaultPreset: 'de'
  #       presets:
  #         'en':
  #           label: 'English'
  #           values: ['en']
  #           uriSegment: 'en'
  Flow:
    http:
      baseUri: 'https://DOMAIN.at/'
  Neos:
    userInterface:
      backendLoginForm:
        backgroundImage: 'resource://CodeQ.Site/Public/Images/LoginScreen.jpg'
    typoScript:
      autoInclude:
        'CodeQ.Site': TRUE
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
