
Neos:
  Flow:
    i18n:
      defaultLocale: de
    mvc:
      routes:
        'Neos.Neos':
          variables:
            # We prefer URLs without the ".html" suffix
            defaultUriSuffix: ''
    error:
      exceptionHandler:
        className: 'Yeebase\Graylog\Error\GraylogExceptionHandler'
        renderingGroups:
          notFoundExceptions:
            options:
              variables:
                path: '404' # skip suffix in notfound as well
    # http:
    #   baseUri: 'https://DOMAIN.at/'
  Neos:
    eventLog:
      enabled: TRUE
    userInterface:
      defaultLanguage: de
    fusion:
      autoInclude:
        CodeQ.Site: true
    nodeTypes:
      groups:
        contentBlocks:
          position: 110
          label: 'Content Blocks'
MOC:
  ImageOptimizer:
    formats:
      'image/jpeg':
        binaryPath: '/usr/bin/jpegtran'
      'image/png':
        binaryPath: '/usr/bin/optipng'
      'image/gif':
        enabled: false
Yeebase:
  Graylog:
    host: '172.17.0.1'
    port: 12201
    chunksize: 'wan'
